### ISSUE TITLE
추가적 기능 구현

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/hisbee#102]
**Description**
새로운 애니메이션 적용

**Todo**
- [x] Footer 애니메이션 적용
- [x] 로그인 폼 , 삭제 폼 , 수정 폼 애니메이션 적용
- [x] 슬라이더 애니메이션 추가
- [x] Nav 부분 애니메이션 수정
