### ISSUE TITLE
추가 작업

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/hisbee#104]
**Description**
해야 하는 짜잘한 작업들

**ToDo**
- [x] 모집글 hover
- [x] radio 버튼 디자인 바꾸기
- [x] 마이페이지 내가 쓴 모집글 , 찜한 모집글 옆으로 넘길 수 있도록
- [x] 마이페이지 사이드 바 , 프로필 부분 디자인 수정
- [x] 모든 페이지 로딩 적용
- [x] 예외 페이지 나왔을 때 메인으로 돌아가기
- [x] signUp 페이지 어떻게 할 지 설정
- [x] 로그인 되었을 때 로그인 버튼 안보이게 하기
- [x] 깡통 api 호출 생각
