### ISSUE TITLE
파이어베이스 연결 , 토큰에 대한 추가 설정 , 슬라이더 추가 설정

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/hisbee#113]
**Descriptiion**
마무리 작업
** ToDo **
- [x] 파이어베이스 연결
- [x] 파이어베이스 이미지 업로드 구현
- [x] 슬라이더 버그 수정
- [x] 토큰에 대한 추가 설정
