### ISSUE TITLE
version2 - 모집글 페이지 수정

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/hisbee#133]
**Description**
- 모집글 필드 변경에 따른 인터페이스와 모집글 정보 수정

**Todo**
- [x] 모집글 인터페이스 변경
- [ ] 모집글 정보 수정
- [ ] 모집글 필터링 기능 수정
- [ ] 모집글 필터링 디자인 수정
