### ISSUE TITLE
테스트 및 기능 추가

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/hisbee#170]
**ToDo**
- [x] 마감 기능 적용
- [x] 마감된 페이지 마감표시 적용
- [x] api 벡엔드 필드 수정에 따른 연결 수정
- [ ] api 테스트 및 버그 수정
- [ ] 라우팅 연결을 통해 모집글 CRUD 플로우 완성
- [ ] 모집글 작성 , 수정에서 옵션 필드 버그 수정 (keywords ,인원 , 학부, 학년)
