### ISSUE TITLE
Validation 적용 , 버그 수정

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/hisbee#241]
**Description**
프로필 생성 , 모집글 생성 및 수정에 대한 Validation 적용
verified 필드의 유무에 따라 본인 글인지 판단 후 기능을 다르게 부여

**Todo**
- [ ] 회원 가입 validation
- [ ] 프로필 validation
- [ ] 모집글 메인에서 글자 수 제한
- [ ] 모집글 생성 validation
- [ ] 모집글 수정 validation
- [ ] verified에 따른 기능 버그 수정
