### ISSUE TITLE
api 연결 마무리

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/hisbee#66]
**Description**
나머지 api 연결

**ToDo**
- [x] #69
- [x] 모집글 수정 , 삭제 api 연결
- [x] 회원 entity interface 생성
- [x] 회원 생성 , 수정 , 삭제 api 연결
