### ISSUE TITLE
인재풀 페이지 필터 기능

### ISSUE THREAD

**Issue by ohinhyuk** [HGU-WALAB/hisbee#72]
**Description**
인재풀 페이지 필터 기능 구현
각종 애니메이션 추가
validation 추가

**Todo**
- [x] 인재풀 페이지 필터 기능 구현
- [x] 헤더 애니메이션 추가
- [x] 로딩 애니메이션 추가
- [x] 검색 애니메이션 추가
- [x] 더 추가할 애니메이션 있는 지 찾아보고 추가하기
- [x] 회원가입 쪽 validation 추가
